import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Nav } from "@/Nav/Nav";
import { AuthProvider } from "./api/auth/nextAuth";
import { Footer } from "@/Nav/Footer";
import { NavProvider } from "@/Nav/context";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({ children }) {
	return (

		<html lang="en">
			<AuthProvider>
				<NavProvider>
					<body className="min-h-screen flex flex-col">
						<Nav />
						{children}
						<Footer />
					</body>
				</NavProvider>
			</AuthProvider>
		</html>

	);
}
